### ISSUE TITLE
Dynamic amounts with placeholders

### ISSUE THREAD

**Issue by Wertik** [devport-space/dock#14]
Implement placeholder parsing into Amount.
Use dynamic amounts where possible.
Allow math expressions in Amount strings.

Example:
```yml
item:
  type: DIAMOND
  amount: %player_level%*2
```
